variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see https://aka.ms/avm/telemetry.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
}

# Define variables for the AVD Host Pool deployment
variable "resource_group_name" {
  type        = string
  description = <<DESCRIPTION
The name of the resource group where the resources will be deployed.
DESCRIPTION 
}

variable "location" {
  type        = string
  description = "The Azure location where the resources will be deployed."
  default     = "eastus2"
}

variable "tags" {
  type        = map(any)
  description = "Map of tags to assign to the Key Vault resource."
  default     = null
}

variable "law_name" {
  type        = string
  description = "The name of the AVD Law."
  default     = "avd-law"
}

variable "law_sku" {
  type        = string
  description = "The SKU of the Law."
  default     = "PerGB2018"
}

variable "law_retention_days" {
  type        = number
  description = "The retention days of the Law."
  default     = 30
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_enabled" {
  type        = bool
  default     = false
  description = "Whether enable tracing tags that generated by BridgeCrew Yor."
  nullable    = false
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_prefix" {
  type        = string
  default     = "avm_"
  description = "Default prefix for generated tracing tags"
  nullable    = false
}