
name: Create Azure Environment

on:
  #schedule:
  #  - cron: "0 13 * * 1-5" # This cron expression corresponds to 8 AM EST (which is 1 PM UTC) from Monday to Friday
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        directory: [ './vwan', './hub&spoke']
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.0

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ matrix.directory }}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{ matrix.directory }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ matrix.directory }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ matrix.directory }}
