name: Destroy Hub&Spoke Environment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    defaults:
       run:
         shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./hub&spoke

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=tfplan
      working-directory: ./hub&spoke

    - name: Terraform Apply Destroy
      run: terraform apply -auto-approve tfplan
      working-directory: ./hub&spoke
