name: Hub and Spoke Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3  # specify the version of Terraform

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/hub&spoke

      - name: Terraform Plan
        run: terraform plan -out:terraform.tfplan
        working-directory: ./terraform/hub&spoke

      - name: Terraform Apply
        run: terraform apply "terraform.tfplan"
        working-directory: ./terraform/hub&spoke

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform/hub&spoke
